build:
  cuda_version: "12.1.1"
  system_packages:
    - "libssl-dev"
    - "libx11-6"
    - "libxext6"
    - "libgl1-mesa-glx"
  python_packages:
    - "git+https://github.com/huggingface/diffusers.git@refs/pull/5895/head"
    - "transformers"
    - "accelerate"
    - "safetensors"
    - "opencv-python"
    - "uuid"